### ISSUE TITLE
app rpi: kivy stalls when quit and relaunched

### ISSUE THREAD

**Issue by RoaddogLabs** [RoaddogLabs/open-race-scale#27]
kivy stalls when ors page is exited on `provider sdl2`

python3 consumes 99% cpu

**Comment by RoaddogLabs** [comment]
resuming with fg spawns 2 python3 procs that consume 100% cpu

resolves by killing procs or bring to foreground and exit

**Comment by RoaddogLabs** [comment]
Result for running hardware with `sim=False`

Running `sim=True` launches as expected

`pi@raspberrypi:~/open-race-scale/software/app $ python3 main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_17-07-14_8.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-287d3b6, 20170710
[INFO   ] [Python      ] v3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
^C Traceback (most recent call last):
   File "main.py", line 193, in <module>
     sc = ScaleControl(simulate=sim)
   File "/home/pi/open-race-scale/software/core/corerp3.py", line 10, in __init__
     self.load_cells = {'FL': LoadCell(17, 27, simulate=simulate),
   File "/home/pi/open-race-scale/software/core/loadcell.py", line 25, in __init__
     self.driver = driver or HX711(dout_pin, pd_sck_pin)
   File "/home/pi/open-race-scale/software/core/hx711.py", line 27, in __init__
     self.set_gain(gain)
   File "/home/pi/open-race-scale/software/core/hx711.py", line 48, in set_gain
     self.read()
   File "/home/pi/open-race-scale/software/core/hx711.py", line 61, in read
     self.wait_for_ready()
   File "/home/pi/open-race-scale/software/core/hx711.py", line 51, in wait_for_ready
     while not self.is_ready():
   File "/home/pi/open-race-scale/software/core/hx711.py", line 30, in is_ready
     def is_ready(self):
 KeyboardInterrupt
[2]+  Terminated              python3 main.py`

**Comment by RoaddogLabs** [comment]
can't replicate so far, did it twice but now runs

**Comment by RoaddogLabs** [comment]
can't replicate over 24 hours, closing
